pipeline {
    agent none

    stages {
        stage('Clone sources') {
            agent any
            steps {
                checkout scm
            }
        }
        stage('Linux') {
            failFast true
            parallel {
                stage('Linux - conancurrent - py27') {
                    agent {
                        label 'Linux'
                    }
                    environment {
                        PYVER = 'py27'
                        TOXENV = 'py27-conancurrent'
                    }
                    steps {
                        sh 'install_linux.sh'
                        sh 'python last_conan_version.py'
                        sh 'tox'
                    }
                }
                stage('Linux - conancurrent - py38') {
                    agent {
                        label 'Linux'
                    }
                    environment {
                        PYVER = 'py38'
                        TOXENV = 'py38-conancurrent'
                    }
                    steps {
                        sh 'install_linux.sh'
                        sh 'python last_conan_version.py'
                        sh 'tox'
                    }
                }
            }
        }
    }
}
