pipeline {
    agent none

    stages {
        stage('Clone sources') {
            agent any
            steps {
                checkout scm
            }
        }
        stage('Linux') {
            failFast true
            parallel {
                stage('Linux - conancurrent') {
                    failFast true
                    parallel {
                        stage('Linux - conancurrent - py27') {
                            agent {
                                dockerfile {
                                    filename 'Dockerfile'
                                    dir '.ci'
                                    label 'conan-hooks'
                                }
                            }
                            environment {
                                PYVER = 'py27'
                                TOXENV = 'py27-conancurrent'
                            }
                            steps {
                                sh 'install_linux.sh'
                                sh 'tox'
                            }
                        }
                        stage('Linux - conancurrent - py38') {
                            agent {
                                dockerfile {
                                    filename 'Dockerfile'
                                    dir '.ci'
                                    label 'conan-hooks'
                                }
                            }
                            environment {
                                PYVER = 'py38'
                                TOXENV = 'py38-conancurrent'
                            }
                            steps {
                                sh 'install_linux.sh'
                                sh 'tox'
                            }
                        }
                    }
                }
            }
        }
    }
}
